### PR TITLE
Add a simple molecule test of munin and munin-node roles

### PR DESCRIPTION
**Pull request by manics**
Some issues have been reported in the IDR munin system, e.g. https://trello.com/c/4Sug86TS/168-munin-is-broken

This adds a simple `molecule` test to provide a baseline if someone else wants to try and fix it.

### CODE REVIEW

**Comment by jburel** [comment]
in order to test this branch on mac
you must have ``ansible 2.2`` installed. This will not work with ``2.1.x`` version (tested with ``2.1.1`` and ``2.1.4``)
see issue https://github.com/ansible/ansible/issues/16352 for error

run ``molecule test``, output:

``
TASK [openmicroscopy.munin-node : Ensure munin-node is running.] ***************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name sysv_exists
fatal: [munin]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_TMGBym/ansible_module_systemd.py\", line 227, in <module>\n    from ansible.module_utils.service import sysv_exists, sysv_is_enabled, fail_if_missing\nImportError: cannot import name sysv_exists\n", "module_stdout": "", "msg": "MODULE FAILURE"}

RUNNING HANDLER [openmicroscopy.munin-node : restart munin-node] ***************

PLAY RECAP *********************************************************************
munin                      : ok=7    changed=4    unreachable=0    failed=1   

``

**Comment by manics** [comment]
Can you try this in a clean virtualenv (without system-site-packages)? also what version of docker?

**Comment by jburel** [comment]
Docker version 1.12.3

**Comment by jburel** [comment]
Same error in a virtualenv w/o system packages.
I have not yet been able to upgrade docker (this could be cause of the issue) due to an error during the upgrade check

**Comment by jburel** [comment]
I have tested with  Docker version 1.12.6 and Docker version 1.12.3 same error

**Comment by manics** [comment]
I'm on docker 1.12.5 and it's working for me.

**Comment by jburel** [comment]
ok will investigate

**Comment by jburel** [comment]
Ok: I found the problem

 * ``molecule 1.18`` requires ``ansibles 2.2`` to avoid issue  https://github.com/ansible/ansible/issues/16352, but the set-up leads to the error described above https://github.com/openmicroscopy/ansible-role-munin/pull/2#issuecomment-273791395
 
So 
 * I installed ``molecule 1.17``, ``ansible 2.1.4``, no error this time
``
PLAY RECAP *********************************************************************
munin                      : ok=16   changed=11   unreachable=0    failed=0
``

The flake8 error:
``RAN: '/usr/local/bin/flake8 tests/test_default.py'
  STDOUT:
tests/test_default.py:10:5: N803 argument name should be lowercase
tests/test_default.py:19:5: N803 argument name should be lowercase
``
This is due to the fact that I have a more "aggressive" flake8 check (i.e. ``flake8 pycodestyle pep8-naming`` are installed) 

You may want to fix that

**Comment by jburel** [comment]
@manics: I have not tested with vagrant. Do you want me to try it too?
Do we have a card or doc to record the set-up required e.g. molecule version, ansible version etc?
cc @joshmoore

**Comment by jburel** [comment]
``
molecule  test --driver vagrant
ERROR: Instance(s) were converged with the 'docker' driver, but the subcommand is using 'vagrant' driver.
``
same if I edit ``molecule.yml``

**Comment by manics** [comment]
`molecule destroy` first?

**Comment by jburel** [comment]
now I am stuck, all the commands return the same i.e. ``molecule destroy``, ``molecule test``.
I understood yesterday and `` test`` was doing a clean as a first step

**Comment by jburel** [comment]
``molecule destroy`` did the trick.
Thanks

**Comment by jburel** [comment]
``molecule  test --driver vagrant
PLAY RECAP *********************************************************************
munin                      : ok=16   changed=11   unreachable=0    failed=0
``

flake8 ("aggressive" check) is the only thing I noticed with this PR.

**Comment by manics** [comment]
```
$ flake8 --version
3.2.1 (pyflakes: 1.3.0, pycodestyle: 2.2.0, mccabe: 0.5.3) CPython 2.7.10 on Darwin
```
What version of `flake8` are you using? The casing of the arguments is correct, it's referring to fixtures (`Service`, `Command`, `File`, `Sudo`) provided by `testinfra` so can't be changed.

**Comment by jburel** [comment]
It has nothing to do with the version of flake8 used.
If the casing of the arguments cannot be changed that's fine.

**Comment by joshmoore** [comment]
So "good to merge" from all (with no version bump)?

**Comment by jburel** [comment]
Good to merge for me

**Comment by jburel** [comment]
@manics Thanks for taking the time to run an intro session
